package perpus;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;

/**
 *
 * @author User
 */
public class frmMain extends javax.swing.JFrame {
    

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel18 = new javax.swing.JLabel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNA = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnbacaan = new javax.swing.JRadioButton();
        btnpelajaran = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        txtjudul = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnnovel = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        txtstatus = new javax.swing.JTextField();
        jcalkembali = new com.toedter.calendar.JDateChooser();
        jcalpinjam = new com.toedter.calendar.JDateChooser();

        jLabel18.setFont(new java.awt.Font("KG Blank Space Solid", 0, 24)); // NOI18N
        jLabel18.setText("FORM BIOADATA SISWA");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel13.setBackground(new java.awt.Color(102, 255, 102));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(410, 300, 40, 40);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(null);
        jPanel5.add(jLabel19);
        jLabel19.setBounds(660, 370, 60, 90);

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setFont(new java.awt.Font("Meltix Bold Demo", 0, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("FORM PENGEMBALIAN BUKU");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(540, 30, 730, 80);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(-190, -30, 1490, 110);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel8.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(510, 30, 40, 40);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(450, 80, 270, 380);

        jLabel3.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel3.setText("No Anggota");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 20, 90, 30);

        txtNA.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNAActionPerformed(evt);
            }
        });
        jPanel1.add(txtNA);
        txtNA.setBounds(130, 20, 210, 30);

        txtNama.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNama);
        txtNama.setBounds(130, 60, 210, 30);

        jLabel4.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel4.setText("Nama Peminjam");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 70, 110, 19);

        buttonGroup2.add(btnbacaan);
        btnbacaan.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        btnbacaan.setText("Buku Bacaan");
        btnbacaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacaanActionPerformed(evt);
            }
        });
        jPanel1.add(btnbacaan);
        btnbacaan.setBounds(130, 230, 140, 27);

        buttonGroup2.add(btnpelajaran);
        btnpelajaran.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        btnpelajaran.setText("Buku Pelajaran");
        btnpelajaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpelajaranActionPerformed(evt);
            }
        });
        jPanel1.add(btnpelajaran);
        btnpelajaran.setBounds(130, 200, 140, 30);

        jLabel14.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel14.setText("Jenis Buku");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 200, 90, 19);

        txtjudul.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        txtjudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjudulActionPerformed(evt);
            }
        });
        jPanel1.add(txtjudul);
        txtjudul.setBounds(130, 310, 210, 30);

        txtAlamat.setColumns(20);
        txtAlamat.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 100, 210, 90);

        jLabel2.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel2.setText("Alamat Peminjam");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 110, 110, 19);

        buttonGroup2.add(btnnovel);
        btnnovel.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        btnnovel.setText("Novel ");
        btnnovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovelActionPerformed(evt);
            }
        });
        jPanel1.add(btnnovel);
        btnnovel.setBounds(130, 250, 140, 40);

        jLabel20.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel20.setText("Judul Buku");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 310, 120, 19);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(20, 20, 350, 380);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jLabel10.setBackground(new java.awt.Color(102, 255, 102));
        jPanel2.add(jLabel10);
        jLabel10.setBounds(510, 30, 40, 40);

        jTable1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NO", "NAMA", "ALAMAT", "JENIS", "JUDUL", "TANGGAL PINJAM", "TANGGAL KEMBALI", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(30, 20, 1190, 170);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(1190, 180, 0, 2);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(20, 410, 1250, 210);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(null);

        jButton3.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton3.setText("PRINT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(30, 30, 110, 40);

        jButton4.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(170, 30, 110, 40);

        jButton5.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton5.setText("UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(310, 30, 110, 40);

        jButton1.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(450, 30, 110, 40);

        jButton2.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton2.setText("REFRESH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(590, 30, 120, 40);

        jButton6.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton6.setText("QUIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(740, 30, 110, 40);

        jPanel4.add(jPanel3);
        jPanel3.setBounds(380, 300, 890, 100);

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setLayout(null);

        jButton7.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton7.setText("SAVE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7);
        jButton7.setBounds(30, 30, 110, 40);

        jButton8.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton8.setText("CLEAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8);
        jButton8.setBounds(170, 30, 110, 40);

        jButton9.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton9.setText("EDIT");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9);
        jButton9.setBounds(310, 30, 110, 40);

        jButton10.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton10.setText("DELETE");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10);
        jButton10.setBounds(450, 30, 110, 40);

        jButton11.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton11.setText("REFRESH");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton11);
        jButton11.setBounds(590, 30, 120, 40);

        jButton12.setFont(new java.awt.Font("Porky's", 0, 18)); // NOI18N
        jButton12.setText("QUIT");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton12);
        jButton12.setBounds(740, 30, 110, 40);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(380, 300, 870, 100);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        jLabel15.setFont(new java.awt.Font("KG Blank Space Solid", 0, 14)); // NOI18N
        jLabel15.setText("Tanggal Pinjam");
        jPanel7.add(jLabel15);
        jLabel15.setBounds(10, 340, 120, 19);

        jLabel17.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tanggal Kembali");
        jPanel7.add(jLabel17);
        jLabel17.setBounds(340, 20, 240, 30);

        jLabel21.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Tanggal Pinjam");
        jPanel7.add(jLabel21);
        jLabel21.setBounds(40, 20, 210, 30);

        status.setFont(new java.awt.Font("Meltix Italic Demo", 1, 48)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setText("STATUS");
        jPanel7.add(status);
        status.setBounds(640, 20, 200, 40);

        txtstatus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(txtstatus);
        txtstatus.setBounds(620, 70, 250, 150);
        jPanel7.add(jcalkembali);
        jcalkembali.setBounds(330, 70, 250, 40);
        jPanel7.add(jcalpinjam);
        jcalpinjam.setBounds(30, 70, 250, 40);

        jPanel4.add(jPanel7);
        jPanel7.setBounds(380, 20, 890, 270);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 80, 1300, 690);

        setSize(new java.awt.Dimension(1310, 762));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNAActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if ("".equals(txtNA.getText()) || "".equals(txtNama.getText()) || "".equals(txtAlamat.getText()) || "".equals(txtjudul.getText())) {
            jOptionPane1.showMessageDialog(this, "Harap Lengkapi Data", "Error", jOptionPane1.WARNING_MESSAGE);
        } else  {
            String JB = "";
                if (btnpelajaran.isSelected()) {
                    JB = "Buku Pelajaran";
                } else if (btnbacaan.isSelected()){
                    JB = "Buku Bacaan";
                } else {
                    JB = "Buku Novel";
                }
               
            SimpleDateFormat date = new SimpleDateFormat("yyy-MM-dd");
            String tgl1 = date.format(jcalpinjam.getDate());
            String tgl2 = date.format(jcalkembali.getDate());
           
            String SQL = "INSERT INTO tb_kembali (No_Anggota,Nama_Peminjam,Alamat_Peminjam,Jenis_Buku,Judul_Buku,Tanggal_Pinjam,Tanggal_Kembali,Status)" + " VALUES ('" + txtNA.getText() 
                    + "','" + txtNama.getText() + "', '" 
                    + txtAlamat.getText()+ "','"
                    + JB + "','"
                    + txtjudul.getText()+"','"
                    + tgl1 +"','"
                    + tgl2 + "','"
                    + txtstatus.getText()+"')";
            
            
            
            int status = KoneksiDB.execute(SQL);
            if (status == 1){
                jOptionPane1.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", jOptionPane1.INFORMATION_MESSAGE);
                selectData();
            } else {
                jOptionPane1.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", jOptionPane1.WARNING_MESSAGE);
            }
            
        
        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int baris = jTable1.getSelectedRow();
        if(baris != -1) {
            String NA = jTable1.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_kembali WHERE No_Anggota='"+NA+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                jOptionPane1.showMessageDialog(this, "Data berhasil dihapus", "Sukses", jOptionPane1.INFORMATION_MESSAGE);
            } else {
                jOptionPane1.showMessageDialog(this, "Data gagal dihapus", "Gagal", jOptionPane1.WARNING_MESSAGE); 
            }
        } else {
            jOptionPane1.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", jOptionPane1.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    
        txtNA.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        buttonGroup2.clearSelection();
        txtjudul.setText("");
        txtstatus.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        selectData();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

     public void selectData(){
        String kolom[] = {"No_Anggota","Nama_Peminjam","Alamat_Peminjam","Jenis_Buku","Judul_Buku","Tanggal_Pinjam","Tanggal_Kembali","Status"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_kembali";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()){
                
                
                String No_Anggota = rs.getString(1);
                String Nama_Peminjam = rs.getString(2);
                String Alamat_Peminjam = rs.getString(3);
                String Jenis_Buku = "";
                if ("Buku Pelajaran".equals(rs.getString(4))) {
                    Jenis_Buku = "Buku Pelajaran";
                } else if ("Buku Bacaan".equals(rs.getString(4))){
                    Jenis_Buku = "Buku Bacaan";
                } else {
                    Jenis_Buku = "Buku Novel";
                }
                String Judul_Buku = rs.getString(5);
                String Tanggal_Pinjam = rs.getString(6);
                String Tanggal_Kembali = rs.getString(7);
                String Status = rs.getString(8);
              
                String data[] = {No_Anggota,Nama_Peminjam,Alamat_Peminjam,Jenis_Buku,Judul_Buku,Tanggal_Pinjam,Tanggal_Kembali,Status};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(dtm);
    }
     
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if ("".equals(txtNA.getText()) || "".equals(txtNama.getText()) || "".equals(txtAlamat.getText()) || "".equals(txtjudul.getText())) {
            jOptionPane1.showMessageDialog(this, "Harap Lengkapi Data", "Error", jOptionPane1.WARNING_MESSAGE);
        } else  {
            String JB = "";
                if (btnpelajaran.isSelected()) {
                    JB = "Buku Pelajaran";
                } else if (btnbacaan.isSelected()){
                    JB = "Buku Bacaan";
                } else {
                    JB = "Buku Novel";
                }
               
            SimpleDateFormat date = new SimpleDateFormat("yyy-MM-dd");
            String tgl1 = date.format(jcalpinjam.getDate());
            String tgl2 = date.format(jcalkembali.getDate());
           
            
            String SQL = "UPDATE `tb_kembali` SET "
                    + "`No_Anggota`="+txtNA.getText()+","
                    + "`Nama_Peminjam`='"+txtNama.getText()+"',"
                    + "`Alamat_Peminjam`='"+txtAlamat.getText()+"',"
                    + "`Jenis_Buku`='"+JB+"',"
                    + "`Judul_Buku`='"+txtjudul.getText()+"',"
                    + "`Tanggal_Pinjam`='"+tgl1+"',"
                    + "`Tanggal_Kembali`='"+tgl2+"' WHERE `No_Anggota`="+txtNA.getText();
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                jOptionPane1.showMessageDialog(this, "Data berhasil diupdate", "Sukses", jOptionPane1.INFORMATION_MESSAGE);
                selectData();
            } else {
                jOptionPane1.showMessageDialog(this, "Data gagal diupdate", "Sukses", jOptionPane1.WARNING_MESSAGE);
            
            }}
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int baris = jTable1.getSelectedRow();
        if (baris != 1|| baris != 0) {
            txtNA.setText(jTable1.getValueAt(baris, 0).toString());
            txtNama.setText(jTable1.getValueAt(baris, 1).toString());
            txtAlamat.setText(jTable1.getValueAt(baris, 2).toString());
            if ("Buku Pelajaran".equals(jTable1.getValueAt(baris, 3).toString())) {
                btnpelajaran.setSelected(true);
            } else if ("Buku Bacaan".equals(jTable1.getValueAt(baris, 3).toString())){
                btnbacaan.setSelected(true);
            } else {
                btnnovel.setSelected(true);
            }
            txtjudul.setText(jTable1.getValueAt(baris, 4).toString());
            SimpleDateFormat date = new SimpleDateFormat("yyy-MM-dd");
            Date tgl1 = null;
            Date tgl2 = null;
            
            try {
                tgl1 = date.parse(jTable1.getValueAt(baris, 5).toString());
                tgl2 = date.parse(jTable1.getValueAt(baris, 6).toString());
            } catch (ParseException ex){
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            jcalpinjam.setDate(tgl1);
            jcalkembali.setDate(tgl2);
            txtstatus.setText(jTable1.getValueAt(baris, 7).toString());
            
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtjudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjudulActionPerformed

    private void btnbacaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbacaanActionPerformed

    private void btnpelajaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpelajaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpelajaranActionPerformed

    private void btnnovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnovelActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnbacaan;
    private javax.swing.JRadioButton btnnovel;
    private javax.swing.JRadioButton btnpelajaran;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jcalkembali;
    private com.toedter.calendar.JDateChooser jcalpinjam;
    private javax.swing.JLabel status;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtNA;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtstatus;
    // End of variables declaration//GEN-END:variables

    

   
}
